# Generated by Django 3.2 on 2021-04-28 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToursNTravels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='departureTime',
        ),
        migrations.RemoveField(
            model_name='train',
            name='departureTime',
        ),
        migrations.AddField(
            model_name='flight',
            name='departureDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='departureDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
