# Generated by Django 3.2 on 2021-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToursNTravels', '0002_auto_20210428_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destinationLocation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sourceLocation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='train',
            name='destinationLocation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='train',
            name='sourceLocation',
            field=models.CharField(max_length=30),
        ),
    ]
