# Generated by Django 3.2 on 2021-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_admin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_admin',
            name='name',
        ),
        migrations.AddField(
            model_name='user_admin',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='email',
            field=models.CharField(max_length=35, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_admin',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
